server:
  port: 80
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
spring:
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
springdoc:
  version: '@springdoc.version@'
  # 多个时, 用逗号分隔
  packages-to-exclude: org.springframework
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: false
  openapi-ui:
    path: /openapi-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true
#    groups-order: DESC
#    operationsSorter: method
  show-actuator: true
  group-configs:
  - group: stores
    paths-to-match: /store/**
  - group: users
    packages-to-scan: org.wapache.openapi.spring.webmvc.demo